import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Link } from 'react-router-dom';
import Badge from '../common/Badge';
import { formatDistanceToNow } from '../../types/date';
export default function EmailList({ emails, loading }) {
    if (loading) {
        return (_jsx("div", { className: "divide-y divide-gray-100", children: [...Array(5)].map((_, i) => (_jsxs("div", { className: "px-6 py-4 flex gap-4 animate-pulse", children: [_jsx("div", { className: "w-8 h-8 bg-gray-200 rounded-full shrink-0" }), _jsxs("div", { className: "flex-1 space-y-2", children: [_jsx("div", { className: "h-4 bg-gray-200 rounded w-3/4" }), _jsx("div", { className: "h-3 bg-gray-100 rounded w-1/2" })] })] }, i))) }));
    }
    if (!emails.length) {
        return (_jsxs("div", { className: "flex flex-col items-center justify-center py-20 text-center", children: [_jsx("div", { className: "text-4xl mb-3", children: "\uD83D\uDCED" }), _jsx("div", { className: "text-gray-500 font-medium", children: "No emails found" }), _jsx("div", { className: "text-gray-400 text-sm mt-1", children: "Try changing your filters or trigger a Gmail fetch" })] }));
    }
    return (_jsx("div", { className: "divide-y divide-gray-100", children: emails.map(email => (_jsxs(Link, { to: `/inbox/${email.id}`, className: "flex items-start gap-4 px-6 py-4 hover:bg-gray-50 transition-colors group", children: [_jsx("div", { className: "w-8 h-8 rounded-full bg-blue-100 flex items-center justify-center text-blue-700 font-medium text-sm shrink-0 mt-0.5", children: email.sender?.[0]?.toUpperCase() ?? '?' }), _jsxs("div", { className: "flex-1 min-w-0", children: [_jsxs("div", { className: "flex items-center justify-between gap-2 mb-1", children: [_jsxs("div", { className: "flex items-center gap-2 min-w-0", children: [_jsx("span", { className: "text-sm font-medium text-gray-900 truncate", children: email.sender }), email.status === 'escalated' && (_jsx("span", { className: "text-xs text-red-600 font-semibold shrink-0", children: "\uD83D\uDEA8 Escalated" }))] }), _jsx("span", { className: "text-xs text-gray-400 shrink-0", children: formatDistanceToNow(email.received_at) })] }), _jsx("div", { className: "text-sm text-gray-800 font-medium truncate mb-1.5", children: email.subject }), _jsxs("div", { className: "text-xs text-gray-500 truncate mb-2", children: [email.body?.slice(0, 120), "..."] }), _jsxs("div", { className: "flex items-center gap-2 flex-wrap", children: [_jsx(Badge, { label: email.status, variant: "status", value: email.status }), email.category && (_jsx(Badge, { label: email.category.replace('_', ' '), variant: "category", value: email.category })), email.sentiment && (_jsx(Badge, { label: email.sentiment, variant: "sentiment", value: email.sentiment })), email.confidence_score != null && (_jsxs("span", { className: "text-xs text-gray-400", children: [Math.round(email.confidence_score), "% confidence"] }))] })] })] }, email.id))) }));
}
