import { jsxs as _jsxs, jsx as _jsx } from "react/jsx-runtime";
import { formatDateTime } from '../../types/date';
import Badge from '../common/Badge';
export default function ThreadView({ emails, currentEmailId }) {
    if (emails.length <= 1)
        return null; // no thread to show if only one message
    return (_jsxs("div", { className: "border rounded-xl bg-white overflow-hidden", children: [_jsx("div", { className: "px-4 py-3 border-b bg-gray-50", children: _jsxs("span", { className: "text-sm font-medium text-gray-700", children: ["Thread history \u00B7 ", emails.length, " messages"] }) }), _jsx("div", { className: "divide-y divide-gray-50", children: emails.map((email, idx) => {
                    const isCurrent = email.id === currentEmailId;
                    return (_jsxs("div", { className: `px-4 py-3 ${isCurrent ? 'bg-blue-50 border-l-2 border-l-blue-500' : 'hover:bg-gray-50'}`, children: [_jsxs("div", { className: "flex items-start justify-between gap-3 mb-1.5", children: [_jsxs("div", { className: "flex items-center gap-2 min-w-0", children: [_jsx("div", { className: "w-6 h-6 rounded-full bg-blue-100 flex items-center justify-center text-blue-700 font-medium text-xs shrink-0", children: email.sender?.[0]?.toUpperCase() ?? '?' }), _jsx("span", { className: "text-sm font-medium text-gray-800 truncate", children: email.sender }), isCurrent && (_jsx("span", { className: "text-xs bg-blue-100 text-blue-700 px-1.5 py-0.5 rounded font-medium shrink-0", children: "Current" }))] }), _jsx("span", { className: "text-xs text-gray-400 shrink-0", children: formatDateTime(email.received_at) })] }), _jsxs("p", { className: "text-xs text-gray-600 ml-8 line-clamp-2 leading-relaxed", children: [email.body?.slice(0, 200), (email.body?.length ?? 0) > 200 ? '…' : ''] }), (email.status || email.sentiment || email.category) && (_jsxs("div", { className: "flex gap-1.5 mt-2 ml-8 flex-wrap", children: [email.status && (_jsx(Badge, { label: email.status, variant: "status", value: email.status })), email.sentiment && (_jsx(Badge, { label: email.sentiment, variant: "sentiment", value: email.sentiment })), email.category && (_jsx(Badge, { label: email.category.replace('_', ' '), variant: "category", value: email.category }))] }))] }, email.id));
                }) })] }));
}
